run_logged $MAITRI_INSTALL/packaging/base.sh
run_logged $MAITRI_INSTALL/packaging/fonts.sh
run_logged $MAITRI_INSTALL/packaging/icons.sh
run_logged $MAITRI_INSTALL/packaging/webapps.sh
run_logged $MAITRI_INSTALL/packaging/tuis.sh
run_logged $MAITRI_INSTALL/packaging/npx.sh
run_logged $MAITRI_INSTALL/packaging/maitri-apps.sh
run_logged $MAITRI_INSTALL/packaging/asus-rog.sh
run_logged $MAITRI_INSTALL/packaging/framework16.sh
run_logged $MAITRI_INSTALL/packaging/dell-xps-touchpad-haptics.sh
run_logged $MAITRI_INSTALL/packaging/surface.sh
