accent = "#644AC9"
cursor = "#635D97"
foreground = "#1F1F1F"
background = "#F5F5F5"
selection_foreground = "#1F1F1F"
selection_background = "#CFCFDE"

color0 = "#F5F5F5"
color1 = "#CB3A2A"
color2 = "#14710A"
color3 = "#846E15"
color4 = "#644AC9"
color5 = "#A3144D"
color6 = "#036A96"
color7 = "#1F1F1F"
color8 = "#FFFFFF"
color9 = "#D74C3D"
color10 = "#198D0C"
color11 = "#9E841A"
color12 = "#7862D0"
color13 = "#BF185A"
color14 = "#047FB4"
color15 = "#2C2B31"
