# Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/

# Use defaults maitri defaults (but don't edit these directly!)
source = ~/.local/share/maitri/default/hypr/autostart.conf
source = ~/.local/share/maitri/default/hypr/bindings/media.conf
source = ~/.local/share/maitri/default/hypr/bindings/clipboard.conf
source = ~/.local/share/maitri/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/maitri/default/hypr/bindings/utilities.conf
source = ~/.local/share/maitri/default/hypr/envs.conf
source = ~/.local/share/maitri/default/hypr/looknfeel.conf
source = ~/.local/share/maitri/default/hypr/input.conf
source = ~/.local/share/maitri/default/hypr/windows.conf
source = ~/.config/maitri/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Toggle config flags dynamically
source = ~/.local/state/maitri/toggles/hypr/*.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu
